if (!requireNamespace("ggplot2", quietly = TRUE)) stop("ggplot2 is required.")
library(ggplot2)

source_dir <- file.path("reports", "output", "chiou_full_reproduction")
asset_dir <- file.path("reports", "assets", "chiou", "v1")
dir.create(asset_dir, recursive = TRUE, showWarnings = FALSE)

fig6 <- read.csv(file.path(source_dir, "fig6_reproduction_summary.csv"),
                 stringsAsFactors = FALSE)
mass <- read.csv(file.path(source_dir, "mass_validation_summary.csv"),
                 stringsAsFactors = FALSE)
fig6$observed_time <- ifelse(is.na(fig6$competition_time), fig6$censored_at,
                             fig6$competition_time)
fig6$status <- ifelse(is.na(fig6$competition_time), "censored", "reached 99:1")
write.csv(fig6, file.path(asset_dir, "fig6_reproduction_summary.csv"), row.names = FALSE)
write.csv(mass, file.path(asset_dir, "mass_validation_summary.csv"), row.names = FALSE)

colours <- c("constant overall concentration" = "#D55E00",
             "constant total M" = "#0072B2",
             "constant protein content in peaks" = "#009E73")
theme_chiou <- theme_minimal(base_size = 12) +
  theme(legend.position = "bottom", panel.grid.minor = element_blank())

p_fig6 <- ggplot(fig6, aes(length, observed_time, colour = control, group = control)) +
  geom_line(linewidth = 0.8) +
  geom_point(aes(shape = status), size = 2.8) +
  scale_y_log10() + scale_colour_manual(values = colours) +
  scale_shape_manual(values = c(censored = 17, `reached 99:1` = 16)) +
  labs(x = "One-dimensional domain length L", y = "Competition time",
       colour = NULL, shape = NULL,
       title = "Published size controls in the Chiou MCAS model",
       subtitle = "Triangle denotes right-censoring at 100,000 time units") + theme_chiou
ggsave(file.path(asset_dir, "fig6_competition_time.png"), p_fig6,
       width = 8.2, height = 5.2, dpi = 180)

p_mass <- ggplot(mass, aes(saturation_index, competition_time)) +
  geom_line(colour = "#6A3D9A", linewidth = 0.8) +
  geom_point(aes(colour = total_mass), size = 3) +
  scale_y_log10() + scale_colour_viridis_c() +
  labs(x = expression(u[max] / u[sat]), y = "Competition time",
       colour = "Total M", title = "Competition slows sharply near saturation") + theme_chiou
ggsave(file.path(asset_dir, "saturation_competition_time.png"), p_mass,
       width = 7.2, height = 4.8, dpi = 180)

selected_keys <- c("L10.00_M020.000", "L15.00_M030.000", "L20.00_M040.000")
profile_rows <- list(); trajectory_rows <- list()
for (key in selected_keys) {
  saved <- readRDS(file.path(source_dir, "checkpoints", paste0(key, ".rds")))
  label <- sprintf("L=%g, M=%g", saved$summary$length, saved$summary$total_mass)
  n <- length(saved$initial_u)
  x <- (seq_len(n) - 0.5) * saved$summary$length / n
  profile_rows[[length(profile_rows) + 1L]] <- data.frame(
    key = key, label = label, x = rep(x, 2),
    state = rep(c("competition start", "simulation end"), each = n),
    u = c(saved$initial_u, saved$final_u))
  trajectory <- saved$trajectory
  keep <- unique(c(seq(1, nrow(trajectory), length.out = min(1000, nrow(trajectory))),
                   nrow(trajectory)))
  keep <- sort(unique(round(keep)))
  trajectory_rows[[length(trajectory_rows) + 1L]] <- data.frame(
    key = key, label = label, trajectory[keep, ])
}
profiles <- do.call(rbind, profile_rows)
trajectories <- do.call(rbind, trajectory_rows)
write.csv(profiles, file.path(asset_dir, "selected_profiles.csv"), row.names = FALSE)
write.csv(trajectories, file.path(asset_dir, "selected_trajectories.csv"), row.names = FALSE)

p_profiles <- ggplot(profiles, aes(x, u, colour = state)) +
  geom_line(linewidth = 0.7) + facet_wrap(~label, scales = "free_x", ncol = 1) +
  scale_colour_manual(values = c(`competition start` = "#0072B2",
                                 `simulation end` = "#D55E00")) +
  labs(x = "Position", y = "Active u", colour = NULL,
       title = "Active profiles before and after competition") + theme_chiou
ggsave(file.path(asset_dir, "selected_profiles.png"), p_profiles,
       width = 7.5, height = 8, dpi = 180)

p_trajectory <- ggplot(trajectories, aes(time, winner_fraction, colour = label)) +
  geom_line(linewidth = 0.8) + geom_hline(yintercept = 0.99, linetype = 2) +
  scale_x_continuous(trans = scales::log1p_trans()) +
  labs(x = "Competition time (log1p scale)", y = "Winner fraction of active excess",
       colour = NULL, title = "Winner accumulation through time") + theme_chiou
ggsave(file.path(asset_dir, "selected_trajectories.png"), p_trajectory,
       width = 8, height = 5, dpi = 180)

writeLines(c(
  "# Chiou MCAS snapshot v1", "",
  "Native 500-bin reproduction outputs generated by scripts/run_chiou_full_reproduction.R.",
  "Figures are generated from the CSV files in this directory by scripts/publish_chiou_snapshot.R.",
  "The L=20 constant-concentration run is right-censored at 100,000 time units."
), file.path(asset_dir, "README.md"))
